language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
  - npm install -g codecov
after_success:
  - npm run coverage
  - ./node_modules/.bin/nyc report --reporter=text-lcov | codecov --pipe